// Extracts the ABIs the front end needs from the Foundry build output.
// Run from web/: node scripts/abis.mjs
import { readFileSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";

const OUT = resolve("../contracts/out");
const CONTRACTS = ["IngotIndex", "IngotMarket", "UnderwriterVault", "HedgedCredit", "MockUSDC"];

const body = CONTRACTS.map((name) => {
  const artifact = JSON.parse(readFileSync(`${OUT}/${name}.sol/${name}.json`, "utf8"));
  return `export const ${name.charAt(0).toLowerCase()}${name.slice(1)}Abi = ${JSON.stringify(
    artifact.abi,
  )} as const;`;
}).join("\n\n");

writeFileSync(
  "lib/abis.ts",
  `// Generated by scripts/abis.mjs — do not edit by hand.\n// Regenerate after any contract change: cd web && node scripts/abis.mjs\n\n${body}\n`,
);
console.log(`wrote lib/abis.ts for ${CONTRACTS.join(", ")}`);
