// Copies the real H100 index series into lib/story-data.ts for the landing page, so the story
// is told with the same 78 days the backtest replays through the contracts.
// Run from web/: node scripts/story.mjs
import { readFileSync, writeFileSync } from "node:fs";

const rows = readFileSync("../contracts/data/h100_index.csv", "utf8").trim().split("\n").slice(1);
const series = rows.map((line) => {
  const [date, price, , samples, sources] = line.split(",");
  return [date, Number(Number(price).toFixed(4)), Number(samples), Number(sources)];
});

writeFileSync(
  "lib/story-data.ts",
  `// Generated by scripts/story.mjs from contracts/data/h100_index.csv. Do not edit.\n` +
    `// [date, USD per GPU-hour, sample count, provider count]\n` +
    `export const INDEX_SERIES: readonly (readonly [string, number, number, number])[] = ${JSON.stringify(series)};\n`,
);
console.log(`wrote lib/story-data.ts (${series.length} days)`);
